/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'surface': '#101415',
        'surface-dim': '#101415',
        'surface-container-lowest': '#0b0f10',
        'surface-container-low': '#191c1e',
        'surface-container': '#1d2022',
        'surface-container-high': '#272a2c',
        'surface-container-highest': '#323537',
        'surface-bright': '#363a3b',
        'surface-variant': '#323537',
        'on-surface': '#e0e3e5',
        'on-surface-variant': '#c2c6d4',
        'outline': '#8c909e',
        'outline-variant': '#424752',
        'primary': '#acc7ff',
        'on-primary': '#002f67',
        'primary-container': '#0056b3',
        'primary-fixed': '#d7e2ff',
        'primary-fixed-dim': '#acc7ff',
        'secondary': '#ddfcff',
        'on-secondary': '#00363a',
        'secondary-container': '#00f1fe',
        'on-secondary-container': '#006a70',
        'secondary-fixed': '#74f5ff',
        'secondary-fixed-dim': '#00dbe7',
        'tertiary': '#bec6e0',
        'tertiary-container': '#50586e',
        'error': '#ffb4ab',
        'on-error': '#690005',
        'error-container': '#93000a',
        'background': '#101415',
        'on-background': '#e0e3e5',
        'inverse-primary': '#115cb9',
      },
      fontFamily: {
        sans: ['Inter', 'Noto Kufi Arabic', 'sans-serif'],
        display: ['Montserrat', 'Noto Kufi Arabic', 'sans-serif'],
      },
    },
  },
  plugins: [],
}
